# Generated by Django 5.2 on 2025-04-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_BE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='subtasks',
            field=models.CharField(default=[]),
        ),
        migrations.DeleteModel(
            name='Subtask',
        ),
    ]
