# Generated by Django 5.2 on 2025-04-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_BE', '0002_tasks_subtasks_delete_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='PositionID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='assigned_to',
            field=models.JSONField(choices=[('alice', 'Alice'), ('bob', 'Bob'), ('carol', 'Carol')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='subtasks',
            field=models.JSONField(default=[]),
        ),
    ]
