# Generated by Django 5.2 on 2025-04-09 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_BE', '0003_tasks_positionid_alter_tasks_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='subtasks',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='PositionID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='assigned_to',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='category',
            field=models.CharField(choices=[('Technical Task', 'Technical Task'), ('User Story', 'User Story')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='prio',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Urgent', 'Urgent')], max_length=10),
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='join_BE.tasks')),
            ],
        ),
    ]
