# Generated by Django 5.2 on 2025-04-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_BE', '0004_remove_tasks_subtasks_alter_tasks_positionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='prio',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], max_length=10),
        ),
    ]
