# Generated by Django 5.1.7 on 2025-04-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_BE', '0007_userprofile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
