# Generated by Django 5.1.7 on 2025-04-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_BE', '0008_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
