# Generated by Django 5.1.7 on 2025-05-05 09:53

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_BE', '0009_remove_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
