# Generated by Django 5.1.7 on 2025-05-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_BE', '0010_alter_contacts_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
